### ISSUE TITLE
GDPR compliant

### ISSUE THREAD

**Issue by zonky2** [skynettechnologies/contao-allinoneaccessibility#1]
The tool currently retrieves various data from the Skynet server and is therefore **currently not GDPR-compliant**.

There should be a variant where all data comes from your own web server.

With the current version, consent would first have to be obtained via a consent banner, which would be an additional hurdle for the target group.

**Comment by skynetindia** [comment]
We have remove the data which are coming from the Skynet server

**Comment by zonky2** [comment]
I add your extension 1.1.4 at Contao 4.13

I see a call to 
`https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-1.svg`

and

![Image](https://github.com/user-attachments/assets/f068f7a2-ece7-4332-b0e7-3851cab7e831)

the call should **not** be made!

**Comment by zonky2** [comment]
It's not enough at version 1.1.5 - see e.g.

* https://github.com/skynettechnologies/contao-allinoneaccessibility/blob/859d4ca97d06c1bf43d5cd38869a8538447cc06f/src/EventListener/AioaTemplateListener.php#L39
* https://github.com/skynettechnologies/contao-allinoneaccessibility/blob/859d4ca97d06c1bf43d5cd38869a8538447cc06f/src/Resources/public/js/aioa.js#L82
* https://github.com/skynettechnologies/contao-allinoneaccessibility/blob/859d4ca97d06c1bf43d5cd38869a8538447cc06f/src/Resources/public/js/aioa.js#L253
* https://www.skynettechnologies.com/accessibility/js/all-in-one-accessibility-js-widget-minify.js

**Comment by skynetindia** [comment]
Thank you for your feedback,  Our development team is reviewing and working on it.

**Comment by rustykowski** [comment]
I just tested the version 1.1.8.
All assets are loaded from https://www.skynettechnologies.com.
The assets should be stored locally in the installation directory of the extension.
Otherwise, the assets would have to be blocked as long as the user has not given their consent via a consent banner, as zonky2 mentioned.
